# Generated by Django 5.2 on 2025-05-02 11:07

import datetime
import django.db.models.deletion
import videoflix_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=videoflix_app.models.video_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoriteVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.customusermodel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoflix_app.video')),
            ],
        ),
        migrations.CreateModel(
            name='UserContinueWatchVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.customusermodel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoflix_app.video')),
            ],
        ),
    ]
